#!/usr/bin/env bash
#

set -e

pushd "$(mktemp -dt scalaz)"
cat >build.sbt <<EOM
scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  "org.scalaz" %% "scalaz-core" % "7.1.1",
  "org.scalaz" %% "scalaz-concurrent" % "7.1.1",
  "org.scalaz" %% "scalaz-effect" % "7.1.1"
)

initialCommands := "import scalaz._, Scalaz._"
EOM

sbt console
popd
